### ISSUE TITLE
source code

### ISSUE THREAD

**Issue by Aprillion** [JeffBeltran/faker.js-docs#31]
Any hints where to find source code of faker.js after https://github.com/Marak/Faker.js has been taken down from the public internet? If yes, changing dead links in this documentation would be fabulous.

The last public version I found is from December 2021 - http://web.archive.org/web/20211218163625/https://github.com/Marak/Faker.js

**Comment by JeffBeltran** [comment]
this is news to me, is there any more info as to why it got taken down? i'll try to dig around and see what happen

**Comment by IanVS** [comment]
The maintainer was pretty bitter about FAANG using it and not paying him anything for it.  Seems something might have broken the camel's back? https://web.archive.org/web/20210801000000/https://github.com/Marak/faker.js/issues/1046.

His personal site is down as well as fakercloud.

**Comment by JeffBeltran** [comment]
yeah i just found this: https://old.reddit.com/r/javascript/comments/jquo97/fakerjs_no_more_free_work_from_marak_pay_me_or/

so looks like he decided it was time to nuke it. Wonder if i have an older copy of it locally, would be a shame if it wasn't forked

**Comment by JeffBeltran** [comment]
while not the same i have used https://www.mockaroo.com/ in the past for similar needs

**Comment by IanVS** [comment]
There were over 2k forks, but finding one that's up-to-date is the tricky part, https://web.archive.org/web/20201104083715/https://github.com/Marak/faker.js/network/members.

Thanks for the suggestion, I was also looking at chance.js, which looks to be a pretty similar, if less popular, alternative.

**Comment by JeffBeltran** [comment]
well looks like he isn't doing so well, so i would not rely on this project anymore https://abc7ny.com/suspicious-package-queens-astoria-fire/6425363/

that being said it looks like this is the defacto fork that will be maintained

https://github.com/withshepherd/faker.js/issues/1

**Comment by IanVS** [comment]
I also stumbled across https://github.com/g45t345rt/minifaker, which I plan to try out.  It's a lot smaller, and is ESM / tree-shakable, and looks like it will meet my needs just fine.

**Comment by JeffBeltran** [comment]
yeah that was referenced in the linked issue, if you have net new project that seems the best route IMO too

**Comment by JeffBeltran** [comment]
the new repo now lives on over at https://github.com/faker-js/faker, new docs based on this are over at https://fakerjs.dev/
