### ISSUE TITLE
Can we update the repo for a newer package?

### ISSUE THREAD

**Issue by luciferreeves** [JeffBeltran/faker.js-docs#32]
I know the author of FakerJS has taken down the code. I have actually forked the repo and made some changes (right now, only name changes) and in future, I am going to port it for Deno too. I'm calling it "bluffmaster" (I suck with unique names, I know). I posted it on NPM too. Here are the links:

GitHub: https://github.com/luciferreeves/bluffmaster
NPM: https://npmjs.com/package/bluffmaster

Can you at least update the docs to show images from the BluffMaster repo instead of the Faker repo? I have already linked your docs to the BluffMaster repo page. 

Cheers!

**Comment by JeffBeltran** [comment]
Thanks @luciferreeves right now im gonna wait and see where this baby should live but once that gets sorted i'll get this updated accordingly. Plus i still want to get the underlining repo updated to v2 of vuepress (https://github.com/vuepress/vuepress-next) but wanted to wait until it gets out of beta

**Comment by luciferreeves** [comment]
Thanks for the update @JeffBeltran

**Comment by TechStudent11** [comment]
@JeffBeltran The new FakerJS package is now being maintained by the public/community.

I've lost the link. If I find it, I'll link it.

**Comment by JeffBeltran** [comment]
yup sorry, i'll get this updated to point to the correct documentation now. The new updated and maintained repo is over at https://github.com/faker-js/faker with the new documentation site at https://fakerjs.dev/
